apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml

images:
- name: ghcr.io/trsenna/notable-2604-beautyplanner/planner-command
  newName: ghcr.io/trsenna/notable-2604-beautyplanner/planner-command
  newTag: sha-5bba0c516421b32f10f7fe610df275798175d069
