apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml
- ingress.yaml

images:
- name: ghcr.io/trsenna/notable-2604-beautyplanner/planner-query
  newName: ghcr.io/trsenna/notable-2604-beautyplanner/planner-query
  newTag: sha-0d50fe4975f60f412fcbd3e526915f355511b3ec
