apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml

images:
  - name: ghcr.io/trsenna/notable-2604-beautyplanner/planner-query
    newTag: sha-0d41a505debc783a2ebf91d95c875615835c76a0
