spring.application.name=planner-sync

management.endpoint.health.probes.enabled=true
management.health.livenessstate.enabled=true
management.health.readinessstate.enabled=true

# Observability - Metrics
management.endpoints.web.exposure.include=health,prometheus
management.prometheus.metrics.export.enabled=true

# Observability - Tracing
management.otlp.tracing.endpoint=http://tempo.monitoring.svc.cluster.local:4318/v1/traces
management.tracing.sampling.probability=1.0

# Logging - Include Trace/Span IDs in console logs for Loki/Promtail
logging.pattern.level=%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]
