apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: planner-query
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/trsenna/notable-2604-beautyplanner.git'
    targetRevision: develop
    path: platform/k8s/planner-query
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: planner
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
